[build]
   adjust this to whatever directory your static site ends up in:
  publish = "public"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-sitemap"

   these inputs are optional; they'll default to:
   buildDir = publish (above)
   filePath = "sitemap.xml"
  [plugins.inputs]
    buildDir = "public"
     filePath = "sitemap.xml"

[build]
  publish = "dist"
  functions = "functions"
   netlify.toml
  command = "npm run build"

 
    

[[headers]]
  for = "/*"
  [headers.values]
  Content-Type = "application/xml"

    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), microphone=()"
    Content-Security-Policy = "default-src 'self'; img-src 'self' https://cdn.example.com; script-src 'self'; style-src 'self';"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    sitemapPath = "sitemap.xml"
    changefreq = "daily"
    priority = 0.5
    trailingSlash = true

[[plugins]]
  package = "@netlify/plugin-minify-html"
  [plugins.inputs]
    minifyJS = true
    minifyCSS = true
    minifyHTML = true

[[plugins]]
  package = "@netlify/plugin-zip-it-and-ship-it"
  [plugins.inputs]
    nodeVersion = "16.x"
    functionsDir = "functions"
    packageManager = "npm"
    packageManagerVersion = "8.x"
    includeFiles = ["dist/**/*", "functions/**/*"]
    excludeFiles = ["node_modules/**/*", "dist/**/*.map", "functions/**/*.map"]
    includeDevDependencies = false
    includeDependencies = true
    includePeerDependencies = false
    includeOptionalDependencies = false
    includeBundledDependencies = false
    includeNodeModules = false
    includePackageJson = true
    includePackageLockJson = true
    includeYarnLock = false                           
  # Removed duplicate [build] section to resolve conflicting keys
  command = "npm run build"

[context.production.environment]
  # pulled from Netlify UI settings
  FB_PAGE_ACCESS_TOKEN = "$FB_PAGE_ACCESS_TOKEN"
  IG_BUSINESS_ACCOUNT_ID = "$IG_BUSINESS_ACCOUNT_ID"
  TWITTER_BEARER_TOKEN = "$TWITTER_BEARER_TOKEN"
  REDDIT_CLIENT_ID = "$REDDIT_CLIENT_ID"
  REDDIT_CLIENT_SECRET = "$REDDIT_CLIENT_SECRET"
  REDDIT_USERNAME = "$REDDIT_USERNAME"
  REDDIT_PASSWORD = "$REDDIT_PASSWORD"
  PINTEREST_ACCESS_TOKEN = "$PINTEREST_ACCESS_TOKEN"
  PINTEREST_BOARD_ID = "$PINTEREST_BOARD_ID"
  SITE_URL = "$SITE_URL"
  SUBREDDIT = "$SUBREDDIT"

[build.processing]
  skip_processing = false

# Run our script after a successful build
[build.lifecycle]
  post_build = "node scripts/postToSocial.js"
